---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/victoriametrics
configMapGenerator:
  - name: victoriametrics-values
    files:
      - values.yaml=victoriametrics-values.yaml
---
