---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vm
  namespace: flux-system
spec:
  interval: 720h
  timeout: 5m
  url: https://victoriametrics.github.io/helm-charts/
---
