---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoriametrics
spec:
  chart:
    spec:
      chart: victoria-metrics-cluster-0.10.0
      version: 'v1.91.3'
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system
      interval: 10m
  interval: 3m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: victoriametrics-values
---
